### ISSUE TITLE
The # field is confusing

### ISSUE THREAD

**Issue by pangolingo** [alexcican/tiii.me#11]
What does this field do? What am I supposed to enter?

I thought maybe it was supposed to be the number of sessions I want to watch the show in. 
But maybe it's the number of episodes I've watched? Or the number of seasons?

**Comment by alexcican** [comment]
Hover over the input and wait for the tooltip. Description is there. Furthermore, this is for TV show fans, and it pre-populates that # field with the max. number of seasons (e.g. “Breaking Bad” -> “5”). If that number can’t go up any further, it must be the seasons, right? Because no “big” show has only 5 episodes.

Number of sessions doesn’t make sense. How would you calculate that?

**Comment by pangolingo** [comment]
I see the tooltip now. Didn't think to look for it, and it could be argued that it's not very obvious. A label above the input field may be a better solution.
