### ISSUE TITLE
Can't share more than the resulting time

### ISSUE THREAD

**Issue by insunaa** [alexcican/tiii.me#5]
Maybe the shows added could also be exported and imported elsewhere destructively or non-destructively as JSON for example.
Maybe I'll do it myself when I have some time and make a pull request...

**Comment by alexcican** [comment]
Why would you need the saved shows?

**Comment by insunaa** [comment]
It's not intended as a primary feature, but I think it'd be nice to share the list of TV shows one has watched with others, to compare with theirs or to introduce them to some of your preferred shows and the other way around. After all it takes quite some time to compile this list, remember all shows that one has watched is especially difficult if your overall time is way past 1 year, like mine.
I don't know if others would care for this feature, haven't analyzed the subject yet, it's just something I personally would enjoy.

**Comment by alexcican** [comment]
Hmm… profiles is something I’ve considered. But you need a server, so given that I host this on GitHub, I can’t create profiles.

**Comment by insunaa** [comment]
Doesn't necessarily have to be a profile, I don't know about the average user, but for a somewhat savvy user export to JSON or export to plain TXT list should be enough

**Comment by danielearena** [comment]
I second d3rrial's proposal. The site is really cool, kudos Alex! I believe that to share the total list of shows would be the natural second step. A (possibly easier) alternative to what d3rrial suggests could be to have a unique URL associated to the list of TV shows watched and the number of seasons for each. No profiles to handle, no exports, just a way to generate a unique URL from the TV shows and retrieve the shows when the URL is called. It's been a while since I did some actual coding, but I believe it's doable.

**Comment by alexcican** [comment]
@danielearena in what format would you want to export the list?

**Comment by insunaa** [comment]
You are already exporting everything as a cookie. I have not yet had the chance to look exactly what format you are using, but I assume it could be easily adapted to fit into JSON or XML, other than that you could make a list that is human readable only which cannot be imported again.

**Comment by danielearena** [comment]
Hi Alex, the list export was more @d3rrial's proposal. He suggested JSON or TXT.

My proposal was more about integrating in the code the possibility of generating a unique URL which, when recalled, would show the list of series and seasons watched. Mathematically, you would need a "bijective function" that uniquely associates a string to an array of series/seasons, something like:

{ ("Lost", 3), ("Friends", 10), ("Breaking Bad", 1) } -> 234jwds0k

And then when you call the URL http://tiii.me/234jwds0k it shows 3 seasons of Lost, 10 of Friends and 1 of Breaking Bad.

Not sure if it's clear... I'd write the code it myself if I had the time or skills, but I'm just dropping this in so that maybe someone can do it.

**Comment by aschemschat** [comment]
I would guess the mainproblem with a url would be to store all information in it. If you just generate a hash, you would have to convert it back to the actuall infos. I havent looked at the code yet so i dont know, if the series-infos fetched have some sort of unique id. If so, you could store something like:
{ ("Lost", 3), ("Friends", 10), ("Breaking Bad", 1) } ->  ((a1,3),(b3,10),(aa,1)) -> a13+b310+aa1
in the url. Maybee skip the +, if you could assume a specified length.
You could just add the plain infos to the url, but i would assume those would be quite long with just a few shows added, maybee to long

**Comment by insunaa** [comment]
The local storage file for only 4 TV shows is already 6KB in size, so I think storage effiency wasn't the main goal here. URL stored lists would be interesting, I'd assume that every show has a unique identifier which I will assume is a 4 byte integer, plus one byte to count the number of seasons, so 5 bytes per dataset / tv show. For encoding it as URL the easiest would probably be base64, every  time the site is called a new API call would have to be made to trakt.tv tho, which I assume to be costly either in bandwidth, or if the API has limited access-attempts, in API fees.

**Comment by alexcican** [comment]
Interesting points, guys. Storage efficiency wasn’t the point, yeah. I just wanted the easiest way to save & read data without doing encoding / decoding and running into issues.

The TV shows have a unique ID that consists of 5 characters. The maximum chars allowed in a URL is around 2,083. So that would give you maximum (roughly) around 297 TV shows.

That is, if you exclude a way of separating them together, and assuming that each TV show has exactly 5 chars for ID, and 2 for # of seasons (example: “04”).

[Math for the above result: (2083 - 8) / 7 = 296.42]

**Comment by insunaa** [comment]
I get 304 TV shows if you encode them as 4 byte integer ID and 1 byte season counter, attach them end-to end, no delimiter and then encode them in base64 and put them behind the URL
(((2083/4)*3)/5)-8

**Comment by alexcican** [comment]
Yeah, I assumed all TV shows have double-digits for seasons counter. Nonetheless, the difference is small. Interesting solution, though.

I might try something once the guys at Trakt implement some caching for the API calls. Because lately, I’ve stressed their servers a lot.

**Comment by insunaa** [comment]
Double digits works for 1 byte. Literally talking about one byte here, 0 to 255 seasons can be accommodated here. You don't need to encode it as a string.
